[package]
name = "rustlike"
version = "0.1.0"
authors = ["Samuel Buzas <buzassg@mail.uc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
